spring.application.name=healthcare-app
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# Silence Hibernate SQL/debug logs in console
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

jwt.secret=404D635166546A576E5A7234753778214125442A472D4B6150645367556B5870
jwt.expiration=86400000
jwt.refresh-expiration=604800000

otp.expiration-minutes=5

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sibiabi2817@gmail.com
spring.mail.password=jrqt ezxi rltt rzwx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=${spring.mail.username:}
app.mail.from-name=Medicore Healthcare

server.port=8088

razorpay.key-id=rzp_test_SiCampDL93pTyP
razorpay.key-secret=0XQcfsHuu0vt3S7BkAP5QDcR
razorpay.api-base-url=https://api.razorpay.com
